"""
Константы модуля Morphological

Содержит все константы используемые в модуле морфологического анализа
"""

# Части речи (Parts of Speech)
POS_NOUN = "NOUN"
POS_VERB = "VERB"
POS_ADJECTIVE = "ADJ"
POS_ADVERB = "ADV"
POS_PRONOUN = "PRON"
POS_PREPOSITION = "PREP"
POS_CONJUNCTION = "CONJ"
POS_PARTICLE = "PART"
POS_INTERJECTION = "INTJ"
POS_NUMERAL = "NUM"
POS_UNKNOWN = "UNKNOWN"

# Допустимые части речи
ALLOWED_POS = [
    POS_NOUN,
    POS_VERB,
    POS_ADJECTIVE,
    POS_ADVERB,
    POS_PRONOUN,
    POS_PREPOSITION,
    POS_CONJUNCTION,
    POS_PARTICLE,
    POS_INTERJECTION,
    POS_NUMERAL,
    POS_UNKNOWN,
]

# Морфологические признаки
FEATURE_CASE_NOMINATIVE = "nomn"
FEATURE_CASE_GENITIVE = "gent"
FEATURE_CASE_DATIVE = "datv"
FEATURE_CASE_ACCUSATIVE = "accs"
FEATURE_CASE_INSTRUMENTAL = "ablt"
FEATURE_CASE_PREPOSITIONAL = "loct"

FEATURE_NUMBER_SINGULAR = "sing"
FEATURE_NUMBER_PLURAL = "plur"

FEATURE_GENDER_MASCULINE = "masc"
FEATURE_GENDER_FEMININE = "femn"
FEATURE_GENDER_NEUTER = "neut"

FEATURE_TENSE_PAST = "past"
FEATURE_TENSE_PRESENT = "pres"
FEATURE_TENSE_FUTURE = "futr"

FEATURE_PERSON_FIRST = "1per"
FEATURE_PERSON_SECOND = "2per"
FEATURE_PERSON_THIRD = "3per"

FEATURE_ASPECT_PERFECTIVE = "perf"
FEATURE_ASPECT_IMPERFECTIVE = "impf"

FEATURE_VOICE_ACTIVE = "actv"
FEATURE_VOICE_PASSIVE = "pssv"

FEATURE_MOOD_INDICATIVE = "indc"
FEATURE_MOOD_IMPERATIVE = "impr"
FEATURE_MOOD_SUBJUNCTIVE = "subj"

# Типы паттернов поиска
PATTERN_TYPE_LEMMA = "lemma"
PATTERN_TYPE_FORM = "form"
PATTERN_TYPE_NOUN_CASE = "noun_case"
PATTERN_TYPE_VERB_TENSE = "verb_tense"
PATTERN_TYPE_ADJ_GENDER = "adj_gender"
PATTERN_TYPE_CUSTOM = "custom"

# Допустимые типы паттернов
ALLOWED_PATTERN_TYPES = [
    PATTERN_TYPE_LEMMA,
    PATTERN_TYPE_FORM,
    PATTERN_TYPE_NOUN_CASE,
    PATTERN_TYPE_VERB_TENSE,
    PATTERN_TYPE_ADJ_GENDER,
    PATTERN_TYPE_CUSTOM,
]

# Поддерживаемые языки
LANGUAGE_RUSSIAN = "ru"
LANGUAGE_ENGLISH = "en"
LANGUAGE_UNKNOWN = "unknown"

SUPPORTED_LANGUAGES = [
    LANGUAGE_RUSSIAN,
    LANGUAGE_ENGLISH,
    LANGUAGE_UNKNOWN,
]

# Типы анализаторов
ANALYZER_PYMYPHORPHY2 = "pymorphy2"
ANALYZER_SPACY = "spacy"
ANALYZER_NLTK = "nltk"
ANALYZER_FALLBACK = "fallback"

# Допустимые анализаторы
ALLOWED_ANALYZERS = [
    ANALYZER_PYMYPHORPHY2,
    ANALYZER_SPACY,
    ANALYZER_NLTK,
    ANALYZER_FALLBACK,
]

# Сообщения об ошибках
ERROR_TEXT_TOO_LONG = "Текст слишком длинный для анализа"
ERROR_WORD_TOO_LONG = "Слово слишком длинное для анализа"
ERROR_INVALID_LANGUAGE = "Неподдерживаемый язык"
ERROR_ANALYZER_NOT_AVAILABLE = "Морфологический анализатор недоступен"
ERROR_BATCH_TOO_LARGE = "Слишком большой пакет для анализа"
ERROR_INVALID_POS = "Неверная часть речи"
ERROR_TEXT_ANALYSIS_FAILED = "Ошибка анализа текста"
ERROR_WORD_ANALYSIS_FAILED = "Ошибка анализа слова"
ERROR_PATTERN_GENERATION_FAILED = "Ошибка генерации паттернов поиска"

# Сообщения об успехе
SUCCESS_WORD_ANALYZED = "Слово успешно проанализировано"
SUCCESS_TEXT_ANALYZED = "Текст успешно проанализирован"
SUCCESS_PATTERNS_GENERATED = "Паттерны поиска успешно сгенерированы"
SUCCESS_KEYWORDS_EXTRACTED = "Ключевые слова успешно извлечены"
SUCCESS_LANGUAGE_DETECTED = "Язык успешно определен"

# Названия полей для API
API_FIELD_WORD = "word"
API_FIELD_LEMMA = "lemma"
API_FIELD_POS = "pos"
API_FIELD_FEATURES = "features"
API_FIELD_FORMS = "forms"
API_FIELD_CONFIDENCE = "confidence"
API_FIELD_ANALYSIS_TIME = "analysis_time"
API_FIELD_TEXT = "text"
API_FIELD_SENTENCES = "sentences"
API_FIELD_WORDS = "words"
API_FIELD_LEMMAS = "lemmas"
API_FIELD_KEYWORDS = "keywords"
API_FIELD_WORD_COUNT = "word_count"
API_FIELD_SENTENCE_COUNT = "sentence_count"
API_FIELD_PATTERNS = "patterns"
API_FIELD_PATTERN_COUNT = "count"
API_FIELD_BASE_WORD = "base_word"
API_FIELD_CASE_SENSITIVE = "case_sensitive"
API_FIELD_WHOLE_WORD = "whole_word"
API_FIELD_INCLUDE_FORMS = "include_forms"
API_FIELD_MAX_KEYWORDS = "max_keywords"
API_FIELD_MIN_KEYWORD_LENGTH = "min_keyword_length"
API_FIELD_POS_FILTER = "pos_filter"
API_FIELD_RESULTS = "results"
API_FIELD_TOTAL_TEXTS = "total_texts"
API_FIELD_SUCCESSFUL_ANALYSES = "successful_analyses"
API_FIELD_FAILED_ANALYSES = "failed_analyses"
API_FIELD_TOTAL_ANALYSIS_TIME = "total_analysis_time"
API_FIELD_DETECTED_LANGUAGE = "detected_language"
API_FIELD_SUPPORTED_LANGUAGES = "supported_languages"
API_FIELD_TOTAL_WORDS_ANALYZED = "total_words_analyzed"
API_FIELD_TOTAL_TEXTS_ANALYZED = "total_texts_analyzed"
API_FIELD_CACHE_HIT_RATE = "cache_hit_rate"
API_FIELD_AVERAGE_ANALYSIS_TIME = "average_analysis_time"
API_FIELD_ANALYZER_VERSION = "analyzer_version"

# Максимальные значения
MAX_TEXT_LENGTH = 10000
MAX_WORD_LENGTH = 100
MAX_BATCH_SIZE = 100
MAX_KEYWORDS = 50
MAX_PATTERNS = 100
MAX_FORMS_PER_WORD = 50

# Настройки кеширования
CACHE_KEY_WORD_ANALYSIS = "morph:word:{word}:{analyzer}"
CACHE_KEY_TEXT_ANALYSIS = "morph:text:{text_hash}:{options}"
CACHE_KEY_WORD_FORMS = "morph:forms:{word}:{analyzer}"
CACHE_KEY_SEARCH_PATTERNS = "morph:patterns:{word}:{options}"

# Таймауты кеша
CACHE_WORD_ANALYSIS_TTL = 1800  # 30 минут
CACHE_TEXT_ANALYSIS_TTL = 900  # 15 минут
CACHE_WORD_FORMS_TTL = 3600  # 1 час
CACHE_SEARCH_PATTERNS_TTL = 3600  # 1 час

# Настройки регулярных выражений
REGEX_TOKENIZE = r"\b\w+\b"
REGEX_SENTENCE_SPLIT = r"(?<=[.!?])\s+"
REGEX_CYRILLIC = r"[\u0400-\u04FF]"
REGEX_PUNCTUATION = r"[^\w\s]"

# Настройки определения языка
LANGUAGE_CYRILLIC_THRESHOLD = 0.3
LANGUAGE_CONFIDENCE_HIGH = 0.8
LANGUAGE_CONFIDENCE_MEDIUM = 0.6
LANGUAGE_CONFIDENCE_LOW = 0.3

# Настройки статистики
STATS_CACHE_SIZE = "cache_size"
STATS_ANALYSIS_COUNT = "analysis_count"
STATS_ERROR_COUNT = "error_count"
STATS_AVERAGE_TIME = "average_time"
STATS_CACHE_HITS = "cache_hits"
STATS_CACHE_MISSES = "cache_misses"

# Настройки логирования
LOG_WORD_ANALYSIS = "Анализ слова: {word} -> {lemma} ({pos})"
LOG_TEXT_ANALYSIS = (
    "Анализ текста: {word_count} слов, {sentence_count} предложений"
)
LOG_PATTERN_GENERATION = "Генерация паттернов: {word} -> {count} паттернов"
LOG_KEYWORD_EXTRACTION = (
    "Извлечение ключевых слов: {keyword_count} из {total_words}"
)
LOG_CACHE_HIT = "Кеш hit: {key}"
LOG_CACHE_MISS = "Кеш miss: {key}"
LOG_ANALYZER_ERROR = "Ошибка анализатора: {error}"

# Настройки метрик
METRIC_WORDS_ANALYZED = "morphological.words.analyzed"
METRIC_TEXTS_ANALYZED = "morphological.texts.analyzed"
METRIC_ANALYSIS_TIME = "morphological.analysis.time"
METRIC_CACHE_HITS = "morphological.cache.hits"
METRIC_CACHE_MISSES = "morphological.cache.misses"
METRIC_ERRORS = "morphological.errors"

# Настройки производительности
PERFORMANCE_ANALYSIS_TIMEOUT = 5.0
PERFORMANCE_BATCH_TIMEOUT = 30.0
PERFORMANCE_MEMORY_LIMIT = 100 * 1024 * 1024  # 100 MB

# Настройки качества анализа
QUALITY_MIN_CONFIDENCE = 0.1
QUALITY_MAX_AMBIGUOUS_PARSES = 5
QUALITY_PREFERRED_PARSE_INDEX = 0


# Экспорт всех констант
__all__ = [
    # Части речи
    "POS_NOUN",
    "POS_VERB",
    "POS_ADJECTIVE",
    "POS_ADVERB",
    "POS_PRONOUN",
    "POS_PREPOSITION",
    "POS_CONJUNCTION",
    "POS_PARTICLE",
    "POS_INTERJECTION",
    "POS_NUMERAL",
    "POS_UNKNOWN",
    "ALLOWED_POS",
    # Морфологические признаки
    "FEATURE_CASE_NOMINATIVE",
    "FEATURE_CASE_GENITIVE",
    "FEATURE_CASE_DATIVE",
    "FEATURE_CASE_ACCUSATIVE",
    "FEATURE_CASE_INSTRUMENTAL",
    "FEATURE_CASE_PREPOSITIONAL",
    "FEATURE_NUMBER_SINGULAR",
    "FEATURE_NUMBER_PLURAL",
    "FEATURE_GENDER_MASCULINE",
    "FEATURE_GENDER_FEMININE",
    "FEATURE_GENDER_NEUTER",
    "FEATURE_TENSE_PAST",
    "FEATURE_TENSE_PRESENT",
    "FEATURE_TENSE_FUTURE",
    "FEATURE_PERSON_FIRST",
    "FEATURE_PERSON_SECOND",
    "FEATURE_PERSON_THIRD",
    "FEATURE_ASPECT_PERFECTIVE",
    "FEATURE_ASPECT_IMPERFECTIVE",
    "FEATURE_VOICE_ACTIVE",
    "FEATURE_VOICE_PASSIVE",
    "FEATURE_MOOD_INDICATIVE",
    "FEATURE_MOOD_IMPERATIVE",
    "FEATURE_MOOD_SUBJUNCTIVE",
    # Типы паттернов
    "PATTERN_TYPE_LEMMA",
    "PATTERN_TYPE_FORM",
    "PATTERN_TYPE_NOUN_CASE",
    "PATTERN_TYPE_VERB_TENSE",
    "PATTERN_TYPE_ADJ_GENDER",
    "PATTERN_TYPE_CUSTOM",
    "ALLOWED_PATTERN_TYPES",
    # Языки
    "LANGUAGE_RUSSIAN",
    "LANGUAGE_ENGLISH",
    "LANGUAGE_UNKNOWN",
    "SUPPORTED_LANGUAGES",
    # Анализаторы
    "ANALYZER_PYMYPHORPHY2",
    "ANALYZER_SPACY",
    "ANALYZER_NLTK",
    "ANALYZER_FALLBACK",
    "ALLOWED_ANALYZERS",
    # Сообщения об ошибках
    "ERROR_TEXT_TOO_LONG",
    "ERROR_WORD_TOO_LONG",
    "ERROR_INVALID_LANGUAGE",
    "ERROR_ANALYZER_NOT_AVAILABLE",
    "ERROR_BATCH_TOO_LARGE",
    "ERROR_INVALID_POS",
    "ERROR_TEXT_ANALYSIS_FAILED",
    "ERROR_WORD_ANALYSIS_FAILED",
    "ERROR_PATTERN_GENERATION_FAILED",
    # Сообщения об успехе
    "SUCCESS_WORD_ANALYZED",
    "SUCCESS_TEXT_ANALYZED",
    "SUCCESS_PATTERNS_GENERATED",
    "SUCCESS_KEYWORDS_EXTRACTED",
    "SUCCESS_LANGUAGE_DETECTED",
    # API поля
    "API_FIELD_WORD",
    "API_FIELD_LEMMA",
    "API_FIELD_POS",
    "API_FIELD_FEATURES",
    "API_FIELD_FORMS",
    "API_FIELD_CONFIDENCE",
    "API_FIELD_ANALYSIS_TIME",
    "API_FIELD_TEXT",
    "API_FIELD_SENTENCES",
    "API_FIELD_WORDS",
    "API_FIELD_LEMMAS",
    "API_FIELD_KEYWORDS",
    "API_FIELD_WORD_COUNT",
    "API_FIELD_SENTENCE_COUNT",
    "API_FIELD_PATTERNS",
    "API_FIELD_PATTERN_COUNT",
    "API_FIELD_BASE_WORD",
    "API_FIELD_CASE_SENSITIVE",
    "API_FIELD_WHOLE_WORD",
    "API_FIELD_INCLUDE_FORMS",
    "API_FIELD_MAX_KEYWORDS",
    "API_FIELD_MIN_KEYWORD_LENGTH",
    "API_FIELD_POS_FILTER",
    "API_FIELD_RESULTS",
    "API_FIELD_TOTAL_TEXTS",
    "API_FIELD_SUCCESSFUL_ANALYSES",
    "API_FIELD_FAILED_ANALYSES",
    "API_FIELD_TOTAL_ANALYSIS_TIME",
    "API_FIELD_DETECTED_LANGUAGE",
    "API_FIELD_SUPPORTED_LANGUAGES",
    "API_FIELD_TOTAL_WORDS_ANALYZED",
    "API_FIELD_TOTAL_TEXTS_ANALYZED",
    "API_FIELD_CACHE_HIT_RATE",
    "API_FIELD_AVERAGE_ANALYSIS_TIME",
    "API_FIELD_ANALYZER_VERSION",
    # Максимальные значения
    "MAX_TEXT_LENGTH",
    "MAX_WORD_LENGTH",
    "MAX_BATCH_SIZE",
    "MAX_KEYWORDS",
    "MAX_PATTERNS",
    "MAX_FORMS_PER_WORD",
    # Кеширование
    "CACHE_KEY_WORD_ANALYSIS",
    "CACHE_KEY_TEXT_ANALYSIS",
    "CACHE_KEY_WORD_FORMS",
    "CACHE_KEY_SEARCH_PATTERNS",
    "CACHE_WORD_ANALYSIS_TTL",
    "CACHE_TEXT_ANALYSIS_TTL",
    "CACHE_WORD_FORMS_TTL",
    "CACHE_SEARCH_PATTERNS_TTL",
    # Регулярные выражения
    "REGEX_TOKENIZE",
    "REGEX_SENTENCE_SPLIT",
    "REGEX_CYRILLIC",
    "REGEX_PUNCTUATION",
    # Определение языка
    "LANGUAGE_CYRILLIC_THRESHOLD",
    "LANGUAGE_CONFIDENCE_HIGH",
    "LANGUAGE_CONFIDENCE_MEDIUM",
    "LANGUAGE_CONFIDENCE_LOW",
    # Статистика
    "STATS_CACHE_SIZE",
    "STATS_ANALYSIS_COUNT",
    "STATS_ERROR_COUNT",
    "STATS_AVERAGE_TIME",
    "STATS_CACHE_HITS",
    "STATS_CACHE_MISSES",
    # Логирование
    "LOG_WORD_ANALYSIS",
    "LOG_TEXT_ANALYSIS",
    "LOG_PATTERN_GENERATION",
    "LOG_KEYWORD_EXTRACTION",
    "LOG_CACHE_HIT",
    "LOG_CACHE_MISS",
    "LOG_ANALYZER_ERROR",
    # Метрики
    "METRIC_WORDS_ANALYZED",
    "METRIC_TEXTS_ANALYZED",
    "METRIC_ANALYSIS_TIME",
    "METRIC_CACHE_HITS",
    "METRIC_CACHE_MISSES",
    "METRIC_ERRORS",
    # Производительность
    "PERFORMANCE_ANALYSIS_TIMEOUT",
    "PERFORMANCE_BATCH_TIMEOUT",
    "PERFORMANCE_MEMORY_LIMIT",
    # Качество анализа
    "QUALITY_MIN_CONFIDENCE",
    "QUALITY_MAX_AMBIGUOUS_PARSES",
    "QUALITY_PREFERRED_PARSE_INDEX",
]
