"""
Константы модуля Keywords

Содержит все константы используемые в модуле управления ключевыми словами
"""

# Лимиты и ограничения
MAX_KEYWORD_LENGTH = 255
MAX_DESCRIPTION_LENGTH = 1000
MAX_CATEGORY_LENGTH = 100
MIN_PRIORITY = 1
MAX_PRIORITY = 10
DEFAULT_PRIORITY = 5

# Пагинация
DEFAULT_LIMIT = 50
MAX_LIMIT = 100
MIN_LIMIT = 1
MIN_OFFSET = 0

# Массовые операции
MAX_KEYWORDS_PER_REQUEST = 100
MAX_BULK_ACTIONS = 100
IMPORT_BATCH_SIZE = 50

# Поиск
SEARCH_TIMEOUT_SECONDS = 5.0
MAX_SEARCH_RESULTS = 200
MIN_SEARCH_QUERY_LENGTH = 1
MAX_SEARCH_QUERY_LENGTH = 255

# Экспорт/импорт
ALLOWED_EXPORT_FORMATS = ["json", "csv", "txt"]
MAX_EXPORT_SIZE = 1000
DEFAULT_EXPORT_FORMAT = "json"

# Кеширование
CACHE_KEYWORD_TTL = 3600  # 1 час
CACHE_SEARCH_TTL = 1800  # 30 минут
CACHE_STATS_TTL = 300  # 5 минут
CACHE_CATEGORY_TTL = 1800  # 30 минут

# Категории
DEFAULT_CATEGORY = "general"
MAX_CATEGORIES_PER_KEYWORD = 1
UNCATEGORIZED_KEYWORDS = "без категории"

# Действия массовых операций
ALLOWED_BULK_ACTIONS = ["activate", "deactivate", "archive", "delete"]
BULK_ACTION_ACTIVATE = "activate"
BULK_ACTION_DEACTIVATE = "deactivate"
BULK_ACTION_ARCHIVE = "archive"
BULK_ACTION_DELETE = "delete"

# Статусы ключевых слов
STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_ARCHIVED = "archived"

# Типы операций
OPERATION_CREATE = "create"
OPERATION_UPDATE = "update"
OPERATION_DELETE = "delete"
OPERATION_ACTIVATE = "activate"
OPERATION_DEACTIVATE = "deactivate"
OPERATION_ARCHIVE = "archive"
OPERATION_SEARCH = "search"
OPERATION_BULK_CREATE = "bulk_create"
OPERATION_BULK_ACTION = "bulk_action"
OPERATION_EXPORT = "export"
OPERATION_IMPORT = "import"

# Сообщения об ошибках
ERROR_KEYWORD_NOT_FOUND = "Ключевое слово не найдено"
ERROR_KEYWORD_ALREADY_EXISTS = "Ключевое слово уже существует"
ERROR_KEYWORD_TOO_LONG = "Ключевое слово слишком длинное"
ERROR_DESCRIPTION_TOO_LONG = "Описание слишком длинное"
ERROR_CATEGORY_TOO_LONG = "Название категории слишком длинное"
ERROR_INVALID_PRIORITY = "Неверный приоритет"
ERROR_INVALID_BULK_SIZE = "Неверный размер пакета"
ERROR_INVALID_FORMAT = "Недопустимый формат"
ERROR_CANNOT_DELETE_ACTIVE = "Нельзя удалять активное ключевое слово"
ERROR_CANNOT_ACTIVATE_ARCHIVED = (
    "Нельзя активировать архивированное ключевое слово"
)
ERROR_BULK_OPERATION_FAILED = "Массовую операцию выполнить не удалось"
ERROR_EXPORT_FAILED = "Экспорт не удался"
ERROR_IMPORT_FAILED = "Импорт не удался"
ERROR_VALIDATION_FAILED = "Валидация не удалась"
ERROR_SEARCH_TIMEOUT = "Превышено время поиска"
ERROR_TOO_MANY_RESULTS = "Слишком много результатов"

# Сообщения об успехе
SUCCESS_KEYWORD_CREATED = "Ключевое слово создано"
SUCCESS_KEYWORD_UPDATED = "Ключевое слово обновлено"
SUCCESS_KEYWORD_DELETED = "Ключевое слово удалено"
SUCCESS_KEYWORD_ACTIVATED = "Ключевое слово активировано"
SUCCESS_KEYWORD_DEACTIVATED = "Ключевое слово деактивировано"
SUCCESS_KEYWORD_ARCHIVED = "Ключевое слово архивировано"
SUCCESS_BULK_OPERATION = "Массовую операцию выполнено успешно"
SUCCESS_EXPORT_COMPLETED = "Экспорт завершен"
SUCCESS_IMPORT_COMPLETED = "Импорт завершен"
SUCCESS_VALIDATION_COMPLETED = "Валидация завершена"

# Названия полей API
API_FIELD_ID = "id"
API_FIELD_WORD = "word"
API_FIELD_CATEGORY = "category"
API_FIELD_DESCRIPTION = "description"
API_FIELD_PRIORITY = "priority"
API_FIELD_STATUS = "status"
API_FIELD_MATCH_COUNT = "match_count"
API_FIELD_CREATED_AT = "created_at"
API_FIELD_UPDATED_AT = "updated_at"
API_FIELD_TOTAL = "total"
API_FIELD_ITEMS = "items"
API_FIELD_LIMIT = "limit"
API_FIELD_OFFSET = "offset"
API_FIELD_HAS_NEXT = "has_next"
API_FIELD_HAS_PREV = "has_prev"
API_FIELD_TOTAL_PAGES = "total_pages"
API_FIELD_PAGE = "page"
API_FIELD_SIZE = "size"

# Регулярные выражения
REGEX_WORD_VALIDATION = r'^[a-zA-Zа-яА-ЯёЁ0-9\s\-_\'"]+$'
REGEX_SEARCH_QUERY = r'^[a-zA-Zа-яА-ЯёЁ0-9\s\-_\'"\.]+$'

# Ключи кеша
CACHE_KEY_KEYWORD = "kw:keyword:{keyword_id}"
CACHE_KEY_KEYWORD_LIST = "kw:list:{filters_hash}"
CACHE_KEY_SEARCH = "kw:search:{query_hash}"
CACHE_KEY_STATS = "kw:stats"
CACHE_KEY_CATEGORIES = "kw:categories"
CACHE_KEY_CATEGORIES_STATS = "kw:categories:stats"

# Метрики
METRIC_KEYWORDS_CREATED = "keywords.created"
METRIC_KEYWORDS_UPDATED = "keywords.updated"
METRIC_KEYWORDS_DELETED = "keywords.deleted"
METRIC_SEARCH_QUERIES = "keywords.search.queries"
METRIC_BULK_OPERATIONS = "keywords.bulk.operations"
METRIC_EXPORT_OPERATIONS = "keywords.export.operations"
METRIC_IMPORT_OPERATIONS = "keywords.import.operations"

# Логи
LOG_KEYWORD_CREATED = "Создано ключевое слово: {word} (ID: {keyword_id})"
LOG_KEYWORD_UPDATED = "Обновлено ключевое слово: {word} (ID: {keyword_id})"
LOG_KEYWORD_DELETED = "Удалено ключевое слово: {word} (ID: {keyword_id})"
LOG_KEYWORD_ACTIVATED = (
    "Активировано ключевое слово: {word} (ID: {keyword_id})"
)
LOG_KEYWORD_DEACTIVATED = (
    "Деактивировано ключевое слово: {word} (ID: {keyword_id})"
)
LOG_KEYWORD_ARCHIVED = "Архивировано ключевое слово: {word} (ID: {keyword_id})"
LOG_BULK_OPERATION = (
    "Массовую операцию '{action}' выполнено: {successful}/{total}"
)
LOG_SEARCH_QUERY = "Поисковый запрос: '{query}' -> {results_count} результатов"
LOG_EXPORT_OPERATION = (
    "Экспорт в формате '{format}': {total_exported} ключевых слов"
)
LOG_IMPORT_OPERATION = (
    "Импорт: {successful} создано, {updated} обновлено, {failed} ошибок"
)

# Настройки валидации
VALIDATION_WORD_MIN_LENGTH = 1
VALIDATION_WORD_MAX_LENGTH = MAX_KEYWORD_LENGTH
VALIDATION_DESCRIPTION_MAX_LENGTH = MAX_DESCRIPTION_LENGTH
VALIDATION_CATEGORY_MAX_LENGTH = MAX_CATEGORY_LENGTH
VALIDATION_PRIORITY_MIN = MIN_PRIORITY
VALIDATION_PRIORITY_MAX = MAX_PRIORITY

# Настройки фильтрации
FILTER_ACTIVE_ONLY_DEFAULT = True
FILTER_PRIORITY_MIN_DEFAULT = MIN_PRIORITY
FILTER_PRIORITY_MAX_DEFAULT = MAX_PRIORITY
FILTER_MATCH_COUNT_MIN_DEFAULT = 0
FILTER_MATCH_COUNT_MAX_DEFAULT = None

# Настройки сортировки
SORT_BY_CREATED_AT = "created_at"
SORT_BY_UPDATED_AT = "updated_at"
SORT_BY_WORD = "word"
SORT_BY_PRIORITY = "priority"
SORT_BY_MATCH_COUNT = "match_count"
SORT_ORDER_ASC = "asc"
SORT_ORDER_DESC = "desc"
DEFAULT_SORT_BY = SORT_BY_CREATED_AT
DEFAULT_SORT_ORDER = SORT_ORDER_DESC

# Настройки импорта
IMPORT_UPDATE_EXISTING_DEFAULT = False
IMPORT_SKIP_DUPLICATES_DEFAULT = True
IMPORT_VALIDATE_DATA_DEFAULT = True

# Настройки экспорта
EXPORT_ACTIVE_ONLY_DEFAULT = True
EXPORT_INCLUDE_STATS_DEFAULT = False
EXPORT_COMPRESS_DEFAULT = False

# Таймауты операций
OPERATION_TIMEOUT_CREATE = 5.0
OPERATION_TIMEOUT_UPDATE = 3.0
OPERATION_TIMEOUT_DELETE = 3.0
OPERATION_TIMEOUT_SEARCH = SEARCH_TIMEOUT_SECONDS
OPERATION_TIMEOUT_BULK = 30.0
OPERATION_TIMEOUT_EXPORT = 60.0
OPERATION_TIMEOUT_IMPORT = 120.0

# Настройки производительности
PERFORMANCE_BATCH_SIZE = 50
PERFORMANCE_CACHE_ENABLED = True
PERFORMANCE_INDEX_ENABLED = False  # Для будущих улучшений
PERFORMANCE_STATS_ENABLED = True

# Настройки безопасности
SECURITY_SANITIZE_INPUT = True
SECURITY_VALIDATE_SQL_INJECTION = True
SECURITY_RATE_LIMIT_ENABLED = False  # Для будущих улучшений
SECURITY_MAX_REQUEST_SIZE = 1024 * 1024  # 1MB

# Настройки мониторинга
MONITORING_ENABLED = True
MONITORING_METRICS_ENABLED = True
MONITORING_HEALTH_CHECK_ENABLED = True
MONITORING_PERFORMANCE_TRACKING = True

# Настройки очистки
CLEANUP_OLD_DATA_ENABLED = False
CLEANUP_RETENTION_DAYS = 365
CLEANUP_BATCH_SIZE = 100


# Экспорт всех констант
__all__ = [
    # Лимиты
    "MAX_KEYWORD_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_CATEGORY_LENGTH",
    "MIN_PRIORITY",
    "MAX_PRIORITY",
    "DEFAULT_PRIORITY",
    # Пагинация
    "DEFAULT_LIMIT",
    "MAX_LIMIT",
    "MIN_LIMIT",
    "MIN_OFFSET",
    # Массовые операции
    "MAX_KEYWORDS_PER_REQUEST",
    "MAX_BULK_ACTIONS",
    "IMPORT_BATCH_SIZE",
    # Поиск
    "SEARCH_TIMEOUT_SECONDS",
    "MAX_SEARCH_RESULTS",
    "MIN_SEARCH_QUERY_LENGTH",
    "MAX_SEARCH_QUERY_LENGTH",
    # Экспорт/импорт
    "ALLOWED_EXPORT_FORMATS",
    "MAX_EXPORT_SIZE",
    "DEFAULT_EXPORT_FORMAT",
    # Кеширование
    "CACHE_KEYWORD_TTL",
    "CACHE_SEARCH_TTL",
    "CACHE_STATS_TTL",
    "CACHE_CATEGORY_TTL",
    # Категории
    "DEFAULT_CATEGORY",
    "MAX_CATEGORIES_PER_KEYWORD",
    "UNCATEGORIZED_KEYWORDS",
    # Действия массовых операций
    "ALLOWED_BULK_ACTIONS",
    "BULK_ACTION_ACTIVATE",
    "BULK_ACTION_DEACTIVATE",
    "BULK_ACTION_ARCHIVE",
    "BULK_ACTION_DELETE",
    # Статусы
    "STATUS_ACTIVE",
    "STATUS_INACTIVE",
    "STATUS_ARCHIVED",
    # Типы операций
    "OPERATION_CREATE",
    "OPERATION_UPDATE",
    "OPERATION_DELETE",
    "OPERATION_ACTIVATE",
    "OPERATION_DEACTIVATE",
    "OPERATION_ARCHIVE",
    "OPERATION_SEARCH",
    "OPERATION_BULK_CREATE",
    "OPERATION_BULK_ACTION",
    "OPERATION_EXPORT",
    "OPERATION_IMPORT",
    # Сообщения об ошибках
    "ERROR_KEYWORD_NOT_FOUND",
    "ERROR_KEYWORD_ALREADY_EXISTS",
    "ERROR_KEYWORD_TOO_LONG",
    "ERROR_DESCRIPTION_TOO_LONG",
    "ERROR_CATEGORY_TOO_LONG",
    "ERROR_INVALID_PRIORITY",
    "ERROR_INVALID_BULK_SIZE",
    "ERROR_INVALID_FORMAT",
    "ERROR_CANNOT_DELETE_ACTIVE",
    "ERROR_CANNOT_ACTIVATE_ARCHIVED",
    "ERROR_BULK_OPERATION_FAILED",
    "ERROR_EXPORT_FAILED",
    "ERROR_IMPORT_FAILED",
    "ERROR_VALIDATION_FAILED",
    "ERROR_SEARCH_TIMEOUT",
    "ERROR_TOO_MANY_RESULTS",
    # Сообщения об успехе
    "SUCCESS_KEYWORD_CREATED",
    "SUCCESS_KEYWORD_UPDATED",
    "SUCCESS_KEYWORD_DELETED",
    "SUCCESS_KEYWORD_ACTIVATED",
    "SUCCESS_KEYWORD_DEACTIVATED",
    "SUCCESS_KEYWORD_ARCHIVED",
    "SUCCESS_BULK_OPERATION",
    "SUCCESS_EXPORT_COMPLETED",
    "SUCCESS_IMPORT_COMPLETED",
    "SUCCESS_VALIDATION_COMPLETED",
    # API поля
    "API_FIELD_ID",
    "API_FIELD_WORD",
    "API_FIELD_CATEGORY",
    "API_FIELD_DESCRIPTION",
    "API_FIELD_PRIORITY",
    "API_FIELD_STATUS",
    "API_FIELD_MATCH_COUNT",
    "API_FIELD_CREATED_AT",
    "API_FIELD_UPDATED_AT",
    "API_FIELD_TOTAL",
    "API_FIELD_ITEMS",
    "API_FIELD_LIMIT",
    "API_FIELD_OFFSET",
    "API_FIELD_HAS_NEXT",
    "API_FIELD_HAS_PREV",
    "API_FIELD_TOTAL_PAGES",
    "API_FIELD_PAGE",
    "API_FIELD_SIZE",
    # Регулярные выражения
    "REGEX_WORD_VALIDATION",
    "REGEX_SEARCH_QUERY",
    # Ключи кеша
    "CACHE_KEY_KEYWORD",
    "CACHE_KEY_KEYWORD_LIST",
    "CACHE_KEY_SEARCH",
    "CACHE_KEY_STATS",
    "CACHE_KEY_CATEGORIES",
    "CACHE_KEY_CATEGORIES_STATS",
    # Метрики
    "METRIC_KEYWORDS_CREATED",
    "METRIC_KEYWORDS_UPDATED",
    "METRIC_KEYWORDS_DELETED",
    "METRIC_SEARCH_QUERIES",
    "METRIC_BULK_OPERATIONS",
    "METRIC_EXPORT_OPERATIONS",
    "METRIC_IMPORT_OPERATIONS",
    # Логи
    "LOG_KEYWORD_CREATED",
    "LOG_KEYWORD_UPDATED",
    "LOG_KEYWORD_DELETED",
    "LOG_KEYWORD_ACTIVATED",
    "LOG_KEYWORD_DEACTIVATED",
    "LOG_KEYWORD_ARCHIVED",
    "LOG_BULK_OPERATION",
    "LOG_SEARCH_QUERY",
    "LOG_EXPORT_OPERATION",
    "LOG_IMPORT_OPERATION",
    # Настройки валидации
    "VALIDATION_WORD_MIN_LENGTH",
    "VALIDATION_WORD_MAX_LENGTH",
    "VALIDATION_DESCRIPTION_MAX_LENGTH",
    "VALIDATION_CATEGORY_MAX_LENGTH",
    "VALIDATION_PRIORITY_MIN",
    "VALIDATION_PRIORITY_MAX",
    # Настройки фильтрации
    "FILTER_ACTIVE_ONLY_DEFAULT",
    "FILTER_PRIORITY_MIN_DEFAULT",
    "FILTER_PRIORITY_MAX_DEFAULT",
    "FILTER_MATCH_COUNT_MIN_DEFAULT",
    "FILTER_MATCH_COUNT_MAX_DEFAULT",
    # Сортировка
    "SORT_BY_CREATED_AT",
    "SORT_BY_UPDATED_AT",
    "SORT_BY_WORD",
    "SORT_BY_PRIORITY",
    "SORT_BY_MATCH_COUNT",
    "SORT_ORDER_ASC",
    "SORT_ORDER_DESC",
    "DEFAULT_SORT_BY",
    "DEFAULT_SORT_ORDER",
    # Импорт
    "IMPORT_UPDATE_EXISTING_DEFAULT",
    "IMPORT_SKIP_DUPLICATES_DEFAULT",
    "IMPORT_VALIDATE_DATA_DEFAULT",
    # Экспорт
    "EXPORT_ACTIVE_ONLY_DEFAULT",
    "EXPORT_INCLUDE_STATS_DEFAULT",
    "EXPORT_COMPRESS_DEFAULT",
    # Таймауты
    "OPERATION_TIMEOUT_CREATE",
    "OPERATION_TIMEOUT_UPDATE",
    "OPERATION_TIMEOUT_DELETE",
    "OPERATION_TIMEOUT_SEARCH",
    "OPERATION_TIMEOUT_BULK",
    "OPERATION_TIMEOUT_EXPORT",
    "OPERATION_TIMEOUT_IMPORT",
    # Производительность
    "PERFORMANCE_BATCH_SIZE",
    "PERFORMANCE_CACHE_ENABLED",
    "PERFORMANCE_INDEX_ENABLED",
    "PERFORMANCE_STATS_ENABLED",
    # Безопасность
    "SECURITY_SANITIZE_INPUT",
    "SECURITY_VALIDATE_SQL_INJECTION",
    "SECURITY_RATE_LIMIT_ENABLED",
    "SECURITY_MAX_REQUEST_SIZE",
    # Мониторинг
    "MONITORING_ENABLED",
    "MONITORING_METRICS_ENABLED",
    "MONITORING_HEALTH_CHECK_ENABLED",
    "MONITORING_PERFORMANCE_TRACKING",
    # Очистка
    "CLEANUP_OLD_DATA_ENABLED",
    "CLEANUP_RETENTION_DAYS",
    "CLEANUP_BATCH_SIZE",
]
