# 🤖 Dependabot автоматические обновления зависимостей
# Документация: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # =============================================================================
  # BACKEND DEPENDENCIES (Python/pip)
  # =============================================================================
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    reviewers:
      - "@andr-235"
    assignees:
      - "@andr-235"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Игнорируем major версии для критических зависимостей
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "alembic"
        update-types: ["version-update:semver-major"]

  # =============================================================================
  # FRONTEND DEPENDENCIES (Node.js/npm)
  # =============================================================================
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    reviewers:
      - "@andr-235"
    assignees:
      - "@andr-235"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Игнорируем major версии для критических зависимостей
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # =============================================================================
  # DOCKER DEPENDENCIES
  # =============================================================================
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "@andr-235"
    assignees:
      - "@andr-235"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "@andr-235"
    assignees:
      - "@andr-235"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
      - "automated"

  # =============================================================================
  # GITHUB ACTIONS DEPENDENCIES
  # =============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "@andr-235"
    assignees:
      - "@andr-235"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
