[build]
# Настройки для сборки Bun

[build.resolve]
# Настройка path aliases для Bun
"@/*" = "./*"
"@/shared/*" = "./shared/*"
"@/shared/lib" = "./shared/lib/index"
"@/shared/lib/*" = "./shared/lib/*"
"@/entities/*" = "./entities/*"

[build.resolve.extensions]
# Расширения файлов для разрешения
".tsx" = "tsx"
".ts" = "ts"
".jsx" = "jsx"
".js" = "js"
".json" = "json"

[build.loader]
# Загрузчики для различных типов файлов
".svg" = "text"
".css" = "css"
".scss" = "css"
".sass" = "css"

[build.define]
# Определения для замены в коде
"NODE_ENV" = "\"production\""
"DOCKER" = "\"true\""