services:
  postgres:
    image: postgres:15-alpine
    container_name: fullstack_prod_postgres
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    expose:
      - "5432"
    networks:
      - prod-db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: fullstack_prod_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ghcr.io/andr-235/fullstack-backend:latest
    container_name: fullstack_prod_backend
    restart: always
    env_file:
      - .env.prod
    environment:
      - ENV=production
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - SERVER_IP=${SERVER_IP}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
    expose:
      - "8000"
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - prod-app-network
      - prod-db-network
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8000/api/v1/health/"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 40s

  arq_worker:
    image: ghcr.io/andr-235/fullstack-arq-worker:latest
    container_name: fullstack_prod_arq_worker
    restart: always
    command: ["python", "-m", "app.workers.arq_worker"]
    env_file:
      - .env.prod
    environment:
      - ENV=production
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - SERVER_IP=${SERVER_IP}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - prod-app-network
      - prod-db-network
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://backend:8000/api/v1/health/"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${DOMAIN}
    container_name: fullstack_prod_frontend
    restart: always
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_IP=${SERVER_IP}
      - NEXT_PUBLIC_API_URL=${DOMAIN}
    expose:
      - "3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: fullstack_prod_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.ip.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./nginx/logs:/var/log/nginx
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://frontend:3000"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 40s

  backup:
    image: postgres:15-alpine
    container_name: fullstack_prod_backup
    restart: "no"
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backup:/backup
      - ./scripts/backup.sh:/backup.sh
    networks:
      - prod-app-network
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "/backup.sh"]
    profiles:
      - backup

networks:
  prod-app-network:
    driver: bridge
  prod-db-network:
    driver: bridge
    internal: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
