services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      # Проверяем наличие .env.dev, если нет - используем .env
      - .env.dev
      - .env
    ports:
      - "3000:3000"
    volumes:
      # Монтируем исходный код для горячей перезагрузки
      - ./backend:/app
      # Создаем именованный volume для node_modules чтобы избежать конфликта архитектур
      - backend_node_modules:/app/node_modules
      # Сохраняем директорию логов
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=development
    # Добавляем команду для запуска в режиме разработки
    command: ["npm", "run", "dev:watch"]
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_started
    env_file:
      # Проверяем наличие .env.dev, если нет - используем .env
      - .env.dev
      - .env
    volumes:
      # Монтируем исходный код для горячей перезагрузки
      - ./frontend:/app
      # Создаем именованный volume для node_modules чтобы избежать конфликта архитектур
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    # Команда уже указана в Dockerfile.dev
    networks:
      - default

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  default:
    driver: bridge