services:
  postgres:
    image: postgres:15-alpine
    container_name: fullstack_prod_postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - prod-db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: fullstack_prod_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fullstack_prod_backend
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - ENV=production
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - SERVER_IP=${SERVER_IP}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
    expose:
      - "8000"
    volumes: []
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - prod-app-network
      - prod-db-network
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8000/api/v1/health/"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 40s

  arq_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.arq
    container_name: fullstack_prod_arq_worker
    restart: unless-stopped
    command: ["arq", "app.workers.arq_worker.WorkerSettings"]
    env_file:
      - .env.prod
    environment:
      - ENV=production
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - SERVER_IP=${SERVER_IP}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
      - ARQ_MAX_JOBS=10
      - ARQ_POLL_DELAY=1.0
      - ARQ_MAX_TRIES=3
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - prod-app-network
      - prod-db-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()",
        ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fullstack_prod_frontend
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_IP=${SERVER_IP}
      - NEXT_PUBLIC_API_URL=${DOMAIN}
      - TMPDIR=/tmp/uploads
    expose:
      - "3000"
    volumes:
      - frontend_temp:/tmp/uploads
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: fullstack_prod_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - prod-app-network
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  backup:
    image: postgres:15-alpine
    container_name: fullstack_prod_backup
    restart: "no"
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backup:/backup
      - ./scripts/backup.sh:/backup.sh
    networks:
      - prod-app-network
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "/backup.sh"]
    profiles:
      - backup

networks:
  prod-app-network:
    driver: bridge
  prod-db-network:
    driver: bridge
    internal: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  frontend_temp:
    driver: local
