"""
Константы модуля Error Reporting

Содержит все константы используемые в модуле отчетов об ошибках
"""

# Статусы отчетов об ошибках
ERROR_REPORT_STATUS_PENDING = "pending"
ERROR_REPORT_STATUS_ACKNOWLEDGED = "acknowledged"
ERROR_REPORT_STATUS_RESOLVED = "resolved"
ERROR_REPORT_STATUS_REOPENED = "reopened"

# Уровни серьезности ошибок
ERROR_SEVERITY_LOW = "low"
ERROR_SEVERITY_MEDIUM = "medium"
ERROR_SEVERITY_HIGH = "high"
ERROR_SEVERITY_CRITICAL = "critical"

# Типы ошибок
ERROR_TYPE_NETWORK = "network"
ERROR_TYPE_DATABASE = "database"
ERROR_TYPE_API = "api"
ERROR_TYPE_VALIDATION = "validation"
ERROR_TYPE_AUTHENTICATION = "authentication"
ERROR_TYPE_AUTHORIZATION = "authorization"
ERROR_TYPE_BUSINESS_LOGIC = "business_logic"
ERROR_TYPE_EXTERNAL_SERVICE = "external_service"
ERROR_TYPE_SYSTEM = "system"
ERROR_TYPE_UNKNOWN = "unknown"

# Источники ошибок
ERROR_SOURCE_USER_REQUEST = "user_request"
ERROR_SOURCE_BACKGROUND_TASK = "background_task"
ERROR_SOURCE_SYSTEM_CHECK = "system_check"
ERROR_SOURCE_EXTERNAL_API = "external_api"
ERROR_SOURCE_DATABASE_OPERATION = "database_operation"
ERROR_SOURCE_UNKNOWN = "unknown"

# Категории ошибок
ERROR_CATEGORY_RUNTIME = "runtime"
ERROR_CATEGORY_CONFIGURATION = "configuration"
ERROR_CATEGORY_SECURITY = "security"
ERROR_CATEGORY_PERFORMANCE = "performance"
ERROR_CATEGORY_INTEGRATION = "integration"
ERROR_CATEGORY_DATA = "data"

# Максимальные значения
MAX_ERROR_MESSAGE_LENGTH = 10000
MAX_STACK_TRACE_LENGTH = 50000
MAX_RESOLUTION_NOTES_LENGTH = 10000
MAX_ADDITIONAL_CONTEXT_SIZE = 50000
MAX_ERROR_REPORTS_PER_PAGE = 100
MAX_ERROR_REPORTS_RETENTION_DAYS = 365
MAX_ERROR_REPORTS_TOTAL = 100000

# Таймауты
ERROR_REPORT_TIMEOUT_ACKNOWLEDGE_HOURS = 24
ERROR_REPORT_TIMEOUT_RESOLVE_HOURS = 168  # 7 дней
ERROR_REPORT_CLEANUP_INTERVAL_HOURS = 24

# Ключи кеша
CACHE_KEY_ERROR_REPORT = "error_report:{report_id}"
CACHE_KEY_ERROR_REPORTS_PAGE = "error_reports:page:{page}:{size}:{filters}"
CACHE_KEY_ERROR_STATS = "error_stats:{days}"
CACHE_KEY_PENDING_REPORTS = "pending_reports:{limit}"
CACHE_KEY_CRITICAL_REPORTS = "critical_reports:{limit}"

# TTL кеша (в секундах)
CACHE_ERROR_REPORT_TTL = 300  # 5 минут
CACHE_ERROR_REPORTS_PAGE_TTL = 60  # 1 минута
CACHE_ERROR_STATS_TTL = 1800  # 30 минут
CACHE_PENDING_REPORTS_TTL = 60  # 1 минута

# Метрики
METRIC_ERROR_REPORTS_TOTAL = "error_reports.total"
METRIC_ERROR_REPORTS_CREATED = "error_reports.created"
METRIC_ERROR_REPORTS_ACKNOWLEDGED = "error_reports.acknowledged"
METRIC_ERROR_REPORTS_RESOLVED = "error_reports.resolved"
METRIC_ERROR_REPORTS_CRITICAL = "error_reports.critical"
METRIC_ERROR_REPORTS_RESPONSE_TIME = "error_reports.response_time"
METRIC_ERROR_REPORTS_BY_TYPE = "error_reports.by_type"
METRIC_ERROR_REPORTS_BY_SEVERITY = "error_reports.by_severity"

# События
EVENT_ERROR_REPORT_CREATED = "error_report.created"
EVENT_ERROR_REPORT_ACKNOWLEDGED = "error_report.acknowledged"
EVENT_ERROR_REPORT_RESOLVED = "error_report.resolved"
EVENT_ERROR_REPORT_REOPENED = "error_report.reopened"
EVENT_ERROR_REPORT_DELETED = "error_report.deleted"
EVENT_ERROR_REPORT_TIMEOUT = "error_report.timeout"

# Права доступа
PERMISSION_ERROR_REPORTS_READ = "error_reports:read"
PERMISSION_ERROR_REPORTS_WRITE = "error_reports:write"
PERMISSION_ERROR_REPORTS_ADMIN = "error_reports:admin"
PERMISSION_ERROR_REPORTS_DELETE = "error_reports:delete"

# Настройки уведомлений
ERROR_NOTIFICATION_ENABLED = True
ERROR_NOTIFICATION_ON_CRITICAL = True
ERROR_NOTIFICATION_ON_TIMEOUT = True
ERROR_NOTIFICATION_CHANNELS = ["log", "email", "webhook"]

# Настройки логирования
ERROR_LOGGING_ENABLED = True
ERROR_LOGGING_LEVEL = "WARNING"
ERROR_LOGGING_INCLUDE_STACK_TRACE = True
ERROR_LOGGING_INCLUDE_CONTEXT = True

# Настройки экспорта
ERROR_EXPORT_FORMATS = ["json", "csv", "xml"]
ERROR_EXPORT_MAX_RECORDS = 10000
ERROR_EXPORT_COMPRESSION = True

# Настройки очистки
ERROR_CLEANUP_ENABLED = True
ERROR_CLEANUP_MAX_AGE_DAYS = 365
ERROR_CLEANUP_BATCH_SIZE = 1000
ERROR_CLEANUP_INTERVAL_HOURS = 24

# Настройки агрегации
ERROR_AGGREGATION_ENABLED = True
ERROR_AGGREGATION_WINDOW_MINUTES = 5
ERROR_AGGREGATION_SIMILARITY_THRESHOLD = 0.8

# Регулярные выражения
REGEX_ERROR_REPORT_ID = (
    r"^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
)
REGEX_EMAIL = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
REGEX_IP_ADDRESS = r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$"

# Сообщения об ошибках
ERROR_INVALID_ERROR_TYPE = "Неверный тип ошибки"
ERROR_INVALID_SEVERITY_LEVEL = "Неверный уровень серьезности"
ERROR_INVALID_REPORT_ID = "Неверный ID отчета об ошибке"
ERROR_REPORT_NOT_FOUND = "Отчет об ошибке не найден"
ERROR_REPORT_ALREADY_ACKNOWLEDGED = "Отчет уже подтвержден"
ERROR_REPORT_ALREADY_RESOLVED = "Отчет уже разрешен"
ERROR_REPORT_NOT_ACKNOWLEDGED = (
    "Отчет должен быть подтвержден перед разрешением"
)
ERROR_UNAUTHORIZED_ACCESS = "Недостаточно прав для доступа к отчетам"
ERROR_INVALID_FILTERS = "Неверные параметры фильтрации"
ERROR_EXPORT_LIMIT_EXCEEDED = "Превышен лимит экспорта"
ERROR_CLEANUP_FAILED = "Не удалось выполнить очистку"

# Сообщения об успехе
SUCCESS_ERROR_REPORT_CREATED = "Отчет об ошибке успешно создан"
SUCCESS_ERROR_REPORT_ACKNOWLEDGED = "Отчет об ошибке подтвержден"
SUCCESS_ERROR_REPORT_RESOLVED = "Отчет об ошибке разрешен"
SUCCESS_ERROR_REPORT_DELETED = "Отчет об ошибке удален"
SUCCESS_ERROR_REPORTS_EXPORTED = "Отчеты об ошибках экспортированы"
SUCCESS_ERROR_REPORTS_CLEANED = "Отчеты об ошибках очищены"

# Настройки по умолчанию
DEFAULT_ERROR_TYPE = ERROR_TYPE_UNKNOWN
DEFAULT_SEVERITY_LEVEL = ERROR_SEVERITY_MEDIUM
DEFAULT_ERROR_SOURCE = ERROR_SOURCE_UNKNOWN
DEFAULT_ERROR_CATEGORY = ERROR_CATEGORY_RUNTIME
DEFAULT_PAGE_SIZE = 20
DEFAULT_MAX_PAGES = 1000

# Экспорт всех констант
__all__ = [
    # Статусы отчетов
    "ERROR_REPORT_STATUS_PENDING",
    "ERROR_REPORT_STATUS_ACKNOWLEDGED",
    "ERROR_REPORT_STATUS_RESOLVED",
    "ERROR_REPORT_STATUS_REOPENED",
    # Уровни серьезности
    "ERROR_SEVERITY_LOW",
    "ERROR_SEVERITY_MEDIUM",
    "ERROR_SEVERITY_HIGH",
    "ERROR_SEVERITY_CRITICAL",
    # Типы ошибок
    "ERROR_TYPE_NETWORK",
    "ERROR_TYPE_DATABASE",
    "ERROR_TYPE_API",
    "ERROR_TYPE_VALIDATION",
    "ERROR_TYPE_AUTHENTICATION",
    "ERROR_TYPE_AUTHORIZATION",
    "ERROR_TYPE_BUSINESS_LOGIC",
    "ERROR_TYPE_EXTERNAL_SERVICE",
    "ERROR_TYPE_SYSTEM",
    "ERROR_TYPE_UNKNOWN",
    # Источники ошибок
    "ERROR_SOURCE_USER_REQUEST",
    "ERROR_SOURCE_BACKGROUND_TASK",
    "ERROR_SOURCE_SYSTEM_CHECK",
    "ERROR_SOURCE_EXTERNAL_API",
    "ERROR_SOURCE_DATABASE_OPERATION",
    "ERROR_SOURCE_UNKNOWN",
    # Категории ошибок
    "ERROR_CATEGORY_RUNTIME",
    "ERROR_CATEGORY_CONFIGURATION",
    "ERROR_CATEGORY_SECURITY",
    "ERROR_CATEGORY_PERFORMANCE",
    "ERROR_CATEGORY_INTEGRATION",
    "ERROR_CATEGORY_DATA",
    # Максимальные значения
    "MAX_ERROR_MESSAGE_LENGTH",
    "MAX_STACK_TRACE_LENGTH",
    "MAX_RESOLUTION_NOTES_LENGTH",
    "MAX_ADDITIONAL_CONTEXT_SIZE",
    "MAX_ERROR_REPORTS_PER_PAGE",
    "MAX_ERROR_REPORTS_RETENTION_DAYS",
    "MAX_ERROR_REPORTS_TOTAL",
    # Таймауты
    "ERROR_REPORT_TIMEOUT_ACKNOWLEDGE_HOURS",
    "ERROR_REPORT_TIMEOUT_RESOLVE_HOURS",
    "ERROR_REPORT_CLEANUP_INTERVAL_HOURS",
    # Ключи кеша
    "CACHE_KEY_ERROR_REPORT",
    "CACHE_KEY_ERROR_REPORTS_PAGE",
    "CACHE_KEY_ERROR_STATS",
    "CACHE_KEY_PENDING_REPORTS",
    "CACHE_KEY_CRITICAL_REPORTS",
    # TTL кеша
    "CACHE_ERROR_REPORT_TTL",
    "CACHE_ERROR_REPORTS_PAGE_TTL",
    "CACHE_ERROR_STATS_TTL",
    "CACHE_PENDING_REPORTS_TTL",
    # Метрики
    "METRIC_ERROR_REPORTS_TOTAL",
    "METRIC_ERROR_REPORTS_CREATED",
    "METRIC_ERROR_REPORTS_ACKNOWLEDGED",
    "METRIC_ERROR_REPORTS_RESOLVED",
    "METRIC_ERROR_REPORTS_CRITICAL",
    "METRIC_ERROR_REPORTS_RESPONSE_TIME",
    "METRIC_ERROR_REPORTS_BY_TYPE",
    "METRIC_ERROR_REPORTS_BY_SEVERITY",
    # События
    "EVENT_ERROR_REPORT_CREATED",
    "EVENT_ERROR_REPORT_ACKNOWLEDGED",
    "EVENT_ERROR_REPORT_RESOLVED",
    "EVENT_ERROR_REPORT_REOPENED",
    "EVENT_ERROR_REPORT_DELETED",
    "EVENT_ERROR_REPORT_TIMEOUT",
    # Права доступа
    "PERMISSION_ERROR_REPORTS_READ",
    "PERMISSION_ERROR_REPORTS_WRITE",
    "PERMISSION_ERROR_REPORTS_ADMIN",
    "PERMISSION_ERROR_REPORTS_DELETE",
    # Настройки уведомлений
    "ERROR_NOTIFICATION_ENABLED",
    "ERROR_NOTIFICATION_ON_CRITICAL",
    "ERROR_NOTIFICATION_ON_TIMEOUT",
    "ERROR_NOTIFICATION_CHANNELS",
    # Настройки логирования
    "ERROR_LOGGING_ENABLED",
    "ERROR_LOGGING_LEVEL",
    "ERROR_LOGGING_INCLUDE_STACK_TRACE",
    "ERROR_LOGGING_INCLUDE_CONTEXT",
    # Настройки экспорта
    "ERROR_EXPORT_FORMATS",
    "ERROR_EXPORT_MAX_RECORDS",
    "ERROR_EXPORT_COMPRESSION",
    # Настройки очистки
    "ERROR_CLEANUP_ENABLED",
    "ERROR_CLEANUP_MAX_AGE_DAYS",
    "ERROR_CLEANUP_BATCH_SIZE",
    "ERROR_CLEANUP_INTERVAL_HOURS",
    # Настройки агрегации
    "ERROR_AGGREGATION_ENABLED",
    "ERROR_AGGREGATION_WINDOW_MINUTES",
    "ERROR_AGGREGATION_SIMILARITY_THRESHOLD",
    # Регулярные выражения
    "REGEX_ERROR_REPORT_ID",
    "REGEX_EMAIL",
    "REGEX_IP_ADDRESS",
    # Сообщения об ошибках
    "ERROR_INVALID_ERROR_TYPE",
    "ERROR_INVALID_SEVERITY_LEVEL",
    "ERROR_INVALID_REPORT_ID",
    "ERROR_REPORT_NOT_FOUND",
    "ERROR_REPORT_ALREADY_ACKNOWLEDGED",
    "ERROR_REPORT_ALREADY_RESOLVED",
    "ERROR_REPORT_NOT_ACKNOWLEDGED",
    "ERROR_UNAUTHORIZED_ACCESS",
    "ERROR_INVALID_FILTERS",
    "ERROR_EXPORT_LIMIT_EXCEEDED",
    "ERROR_CLEANUP_FAILED",
    # Сообщения об успехе
    "SUCCESS_ERROR_REPORT_CREATED",
    "SUCCESS_ERROR_REPORT_ACKNOWLEDGED",
    "SUCCESS_ERROR_REPORT_RESOLVED",
    "SUCCESS_ERROR_REPORT_DELETED",
    "SUCCESS_ERROR_REPORTS_EXPORTED",
    "SUCCESS_ERROR_REPORTS_CLEANED",
    # Настройки по умолчанию
    "DEFAULT_ERROR_TYPE",
    "DEFAULT_SEVERITY_LEVEL",
    "DEFAULT_ERROR_SOURCE",
    "DEFAULT_ERROR_CATEGORY",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_MAX_PAGES",
]
