"""
Константы модуля Health

Содержит все константы используемые в модуле проверки здоровья системы
"""

# Статусы здоровья
HEALTH_STATUS_HEALTHY = "healthy"
HEALTH_STATUS_DEGRADED = "degraded"
HEALTH_STATUS_UNHEALTHY = "unhealthy"
HEALTH_STATUS_UNKNOWN = "unknown"
HEALTH_STATUS_READY = "ready"
HEALTH_STATUS_NOT_READY = "not_ready"
HEALTH_STATUS_ALIVE = "alive"
HEALTH_STATUS_DEAD = "dead"
HEALTH_STATUS_WARNING = "warning"
HEALTH_STATUS_CRITICAL = "critical"

# Типы проверок здоровья
HEALTH_CHECK_TYPE_BASIC = "basic"
HEALTH_CHECK_TYPE_DETAILED = "detailed"
HEALTH_CHECK_TYPE_READINESS = "readiness"
HEALTH_CHECK_TYPE_LIVENESS = "liveness"
HEALTH_CHECK_TYPE_STARTUP = "startup"

# Компоненты системы
HEALTH_COMPONENT_DATABASE = "database"
HEALTH_COMPONENT_REDIS = "redis"
HEALTH_COMPONENT_VK_API = "vk_api"
HEALTH_COMPONENT_MEMORY = "memory"
HEALTH_COMPONENT_DISK = "disk"
HEALTH_COMPONENT_CPU = "cpu"
HEALTH_COMPONENT_NETWORK = "network"
HEALTH_COMPONENT_PROCESS = "process"
HEALTH_COMPONENT_API = "api"
HEALTH_COMPONENT_CACHE = "cache"
HEALTH_COMPONENT_QUEUE = "queue"
HEALTH_COMPONENT_WORKER = "worker"
HEALTH_COMPONENT_SCHEDULER = "scheduler"
HEALTH_COMPONENT_LOGGING = "logging"
HEALTH_COMPONENT_METRICS = "metrics"

# Пороги для метрик
MEMORY_CRITICAL_THRESHOLD = 90.0  # %
MEMORY_WARNING_THRESHOLD = 80.0  # %
DISK_CRITICAL_THRESHOLD = 95.0  # %
DISK_WARNING_THRESHOLD = 85.0  # %
CPU_CRITICAL_THRESHOLD = 95.0  # %
CPU_WARNING_THRESHOLD = 80.0  # %
NETWORK_TIMEOUT_CRITICAL = 30.0  # seconds
NETWORK_TIMEOUT_WARNING = 10.0  # seconds

# Временные интервалы
HEALTH_CHECK_INTERVAL = 30  # seconds
HEALTH_CHECK_TIMEOUT = 10  # seconds
HEALTH_CACHE_TTL = 60  # seconds
HEALTH_HISTORY_RETENTION = 3600  # seconds (1 hour)
HEALTH_METRICS_INTERVAL = 60  # seconds

# Максимальные значения
MAX_RESPONSE_TIME_MS = 5000  # 5 seconds
MAX_HEALTH_CHECKS = 1000
MAX_HEALTH_HISTORY = 100
MAX_COMPONENT_CHECKS = 50
MAX_METRIC_VALUES = 1000

# Коды ошибок здоровья
HEALTH_ERROR_TIMEOUT = "TIMEOUT"
HEALTH_ERROR_CONNECTION_FAILED = "CONNECTION_FAILED"
HEALTH_ERROR_INVALID_RESPONSE = "INVALID_RESPONSE"
HEALTH_ERROR_CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
HEALTH_ERROR_RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
HEALTH_ERROR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
HEALTH_ERROR_UNKNOWN_COMPONENT = "UNKNOWN_COMPONENT"

# Сообщения об ошибках
ERROR_HEALTH_CHECK_FAILED = "Health check failed"
ERROR_HEALTH_COMPONENT_NOT_FOUND = "Health component not found"
ERROR_HEALTH_CHECK_TIMEOUT = "Health check timeout"
ERROR_HEALTH_INVALID_CONFIGURATION = "Invalid health check configuration"
ERROR_HEALTH_SERVICE_UNAVAILABLE = "Health service unavailable"
ERROR_HEALTH_METRICS_UNAVAILABLE = "Health metrics unavailable"

# Сообщения об успехе
SUCCESS_HEALTH_CHECK_PASSED = "Health check passed"
SUCCESS_HEALTH_ALL_COMPONENTS_HEALTHY = "All components are healthy"
SUCCESS_HEALTH_SYSTEM_READY = "System is ready"
SUCCESS_HEALTH_SYSTEM_ALIVE = "System is alive"

# Регулярные выражения
REGEX_COMPONENT_NAME = r"^[a-zA-Z][a-zA-Z0-9_-]*$"
REGEX_HEALTH_STATUS = r"^(healthy|degraded|unhealthy|unknown|ready|not_ready|alive|dead|warning|critical)$"

# Ключи кеша
CACHE_KEY_HEALTH_STATUS = "health:status"
CACHE_KEY_HEALTH_COMPONENT = "health:component:{component}"
CACHE_KEY_HEALTH_HISTORY = "health:history"
CACHE_KEY_HEALTH_METRICS = "health:metrics"
CACHE_KEY_HEALTH_LAST_CHECK = "health:last_check"

# TTL кеша (в секундах)
CACHE_HEALTH_STATUS_TTL = 30
CACHE_HEALTH_COMPONENT_TTL = 60
CACHE_HEALTH_METRICS_TTL = 300

# Метрики
METRIC_HEALTH_CHECKS_TOTAL = "health.checks.total"
METRIC_HEALTH_CHECKS_SUCCESSFUL = "health.checks.successful"
METRIC_HEALTH_CHECKS_FAILED = "health.checks.failed"
METRIC_HEALTH_RESPONSE_TIME = "health.response_time"
METRIC_HEALTH_COMPONENT_STATUS = "health.component.status"
METRIC_HEALTH_SYSTEM_UPTIME = "health.system.uptime"
METRIC_HEALTH_MEMORY_USAGE = "health.memory.usage"
METRIC_HEALTH_DISK_USAGE = "health.disk.usage"
METRIC_HEALTH_CPU_USAGE = "health.cpu.usage"

# События
EVENT_HEALTH_STATUS_CHANGED = "health.status.changed"
EVENT_HEALTH_COMPONENT_FAILED = "health.component.failed"
EVENT_HEALTH_COMPONENT_RECOVERED = "health.component.recovered"
EVENT_HEALTH_CHECK_TIMEOUT = "health.check.timeout"
EVENT_HEALTH_SYSTEM_DEGRADED = "health.system.degraded"
EVENT_HEALTH_SYSTEM_RECOVERED = "health.system.recovered"

# Уровни логирования для здоровья
LOG_LEVEL_HEALTHY = "INFO"
LOG_LEVEL_DEGRADED = "WARNING"
LOG_LEVEL_UNHEALTHY = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# Настройки экспорта
HEALTH_EXPORT_FORMAT_JSON = "json"
HEALTH_EXPORT_FORMAT_PROMETHEUS = "prometheus"
HEALTH_EXPORT_FORMAT_XML = "xml"

# Настройки уведомлений
HEALTH_NOTIFICATION_ENABLED = True
HEALTH_NOTIFICATION_ON_FAILURE = True
HEALTH_NOTIFICATION_ON_RECOVERY = True
HEALTH_NOTIFICATION_CHANNELS = ["log", "email", "webhook"]

# Настройки зависимостей
HEALTH_DEPENDENCY_DATABASE_REQUIRED = True
HEALTH_DEPENDENCY_REDIS_REQUIRED = False
HEALTH_DEPENDENCY_VK_API_REQUIRED = False
HEALTH_DEPENDENCY_CACHE_REQUIRED = False

# Настройки повторных попыток
HEALTH_RETRY_ENABLED = True
HEALTH_RETRY_MAX_ATTEMPTS = 3
HEALTH_RETRY_BACKOFF_FACTOR = 2.0
HEALTH_RETRY_MAX_DELAY = 30.0

# Настройки для Kubernetes
K8S_READINESS_PATH = "/health/ready"
K8S_LIVENESS_PATH = "/health/live"
K8S_STARTUP_PATH = "/health/startup"

# Настройки для Prometheus
PROMETHEUS_METRICS_ENABLED = True
PROMETHEUS_METRICS_PATH = "/metrics"
PROMETHEUS_METRICS_PREFIX = "vk_comments_parser"

# Экспорт всех констант
__all__ = [
    # Статусы здоровья
    "HEALTH_STATUS_HEALTHY",
    "HEALTH_STATUS_DEGRADED",
    "HEALTH_STATUS_UNHEALTHY",
    "HEALTH_STATUS_UNKNOWN",
    "HEALTH_STATUS_READY",
    "HEALTH_STATUS_NOT_READY",
    "HEALTH_STATUS_ALIVE",
    "HEALTH_STATUS_DEAD",
    "HEALTH_STATUS_WARNING",
    "HEALTH_STATUS_CRITICAL",
    # Типы проверок здоровья
    "HEALTH_CHECK_TYPE_BASIC",
    "HEALTH_CHECK_TYPE_DETAILED",
    "HEALTH_CHECK_TYPE_READINESS",
    "HEALTH_CHECK_TYPE_LIVENESS",
    "HEALTH_CHECK_TYPE_STARTUP",
    # Компоненты системы
    "HEALTH_COMPONENT_DATABASE",
    "HEALTH_COMPONENT_REDIS",
    "HEALTH_COMPONENT_VK_API",
    "HEALTH_COMPONENT_MEMORY",
    "HEALTH_COMPONENT_DISK",
    "HEALTH_COMPONENT_CPU",
    "HEALTH_COMPONENT_NETWORK",
    "HEALTH_COMPONENT_PROCESS",
    "HEALTH_COMPONENT_API",
    "HEALTH_COMPONENT_CACHE",
    "HEALTH_COMPONENT_QUEUE",
    "HEALTH_COMPONENT_WORKER",
    "HEALTH_COMPONENT_SCHEDULER",
    "HEALTH_COMPONENT_LOGGING",
    "HEALTH_COMPONENT_METRICS",
    # Пороги для метрик
    "MEMORY_CRITICAL_THRESHOLD",
    "MEMORY_WARNING_THRESHOLD",
    "DISK_CRITICAL_THRESHOLD",
    "DISK_WARNING_THRESHOLD",
    "CPU_CRITICAL_THRESHOLD",
    "CPU_WARNING_THRESHOLD",
    "NETWORK_TIMEOUT_CRITICAL",
    "NETWORK_TIMEOUT_WARNING",
    # Временные интервалы
    "HEALTH_CHECK_INTERVAL",
    "HEALTH_CHECK_TIMEOUT",
    "HEALTH_CACHE_TTL",
    "HEALTH_HISTORY_RETENTION",
    "HEALTH_METRICS_INTERVAL",
    # Максимальные значения
    "MAX_RESPONSE_TIME_MS",
    "MAX_HEALTH_CHECKS",
    "MAX_HEALTH_HISTORY",
    "MAX_COMPONENT_CHECKS",
    "MAX_METRIC_VALUES",
    # Коды ошибок здоровья
    "HEALTH_ERROR_TIMEOUT",
    "HEALTH_ERROR_CONNECTION_FAILED",
    "HEALTH_ERROR_INVALID_RESPONSE",
    "HEALTH_ERROR_CONFIGURATION_ERROR",
    "HEALTH_ERROR_RESOURCE_EXHAUSTED",
    "HEALTH_ERROR_SERVICE_UNAVAILABLE",
    "HEALTH_ERROR_UNKNOWN_COMPONENT",
    # Сообщения об ошибках
    "ERROR_HEALTH_CHECK_FAILED",
    "ERROR_HEALTH_COMPONENT_NOT_FOUND",
    "ERROR_HEALTH_CHECK_TIMEOUT",
    "ERROR_HEALTH_INVALID_CONFIGURATION",
    "ERROR_HEALTH_SERVICE_UNAVAILABLE",
    "ERROR_HEALTH_METRICS_UNAVAILABLE",
    # Сообщения об успехе
    "SUCCESS_HEALTH_CHECK_PASSED",
    "SUCCESS_HEALTH_ALL_COMPONENTS_HEALTHY",
    "SUCCESS_HEALTH_SYSTEM_READY",
    "SUCCESS_HEALTH_SYSTEM_ALIVE",
    # Регулярные выражения
    "REGEX_COMPONENT_NAME",
    "REGEX_HEALTH_STATUS",
    # Ключи кеша
    "CACHE_KEY_HEALTH_STATUS",
    "CACHE_KEY_HEALTH_COMPONENT",
    "CACHE_KEY_HEALTH_HISTORY",
    "CACHE_KEY_HEALTH_METRICS",
    "CACHE_KEY_HEALTH_LAST_CHECK",
    # TTL кеша
    "CACHE_HEALTH_STATUS_TTL",
    "CACHE_HEALTH_COMPONENT_TTL",
    "CACHE_HEALTH_METRICS_TTL",
    # Метрики
    "METRIC_HEALTH_CHECKS_TOTAL",
    "METRIC_HEALTH_CHECKS_SUCCESSFUL",
    "METRIC_HEALTH_CHECKS_FAILED",
    "METRIC_HEALTH_RESPONSE_TIME",
    "METRIC_HEALTH_COMPONENT_STATUS",
    "METRIC_HEALTH_SYSTEM_UPTIME",
    "METRIC_HEALTH_MEMORY_USAGE",
    "METRIC_HEALTH_DISK_USAGE",
    "METRIC_HEALTH_CPU_USAGE",
    # События
    "EVENT_HEALTH_STATUS_CHANGED",
    "EVENT_HEALTH_COMPONENT_FAILED",
    "EVENT_HEALTH_COMPONENT_RECOVERED",
    "EVENT_HEALTH_CHECK_TIMEOUT",
    "EVENT_HEALTH_SYSTEM_DEGRADED",
    "EVENT_HEALTH_SYSTEM_RECOVERED",
    # Уровни логирования для здоровья
    "LOG_LEVEL_HEALTHY",
    "LOG_LEVEL_DEGRADED",
    "LOG_LEVEL_UNHEALTHY",
    "LOG_LEVEL_CRITICAL",
    # Настройки экспорта
    "HEALTH_EXPORT_FORMAT_JSON",
    "HEALTH_EXPORT_FORMAT_PROMETHEUS",
    "HEALTH_EXPORT_FORMAT_XML",
    # Настройки уведомлений
    "HEALTH_NOTIFICATION_ENABLED",
    "HEALTH_NOTIFICATION_ON_FAILURE",
    "HEALTH_NOTIFICATION_ON_RECOVERY",
    "HEALTH_NOTIFICATION_CHANNELS",
    # Настройки зависимостей
    "HEALTH_DEPENDENCY_DATABASE_REQUIRED",
    "HEALTH_DEPENDENCY_REDIS_REQUIRED",
    "HEALTH_DEPENDENCY_VK_API_REQUIRED",
    "HEALTH_DEPENDENCY_CACHE_REQUIRED",
    # Настройки повторных попыток
    "HEALTH_RETRY_ENABLED",
    "HEALTH_RETRY_MAX_ATTEMPTS",
    "HEALTH_RETRY_BACKOFF_FACTOR",
    "HEALTH_RETRY_MAX_DELAY",
    # Настройки для Kubernetes
    "K8S_READINESS_PATH",
    "K8S_LIVENESS_PATH",
    "K8S_STARTUP_PATH",
    # Настройки для Prometheus
    "PROMETHEUS_METRICS_ENABLED",
    "PROMETHEUS_METRICS_PATH",
    "PROMETHEUS_METRICS_PREFIX",
]
