name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["andr-235"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running?
      options:
        - 1.0.0 (Default)
        - 1.1.0
        - 2.0.0
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 📋 Краткое описание
      description: Краткое описание проблемы
      placeholder: Опишите что пошло не так...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Что должно было произойти
      placeholder: Опишите ожидаемый результат...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактическое поведение
      description: Что произошло на самом деле
      placeholder: Опишите что происходит вместо ожидаемого...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Шаги для воспроизведения
      description: Пошаговая инструкция для воспроизведения ошибки
      placeholder: |
        1. Перейти к '...'
        2. Кликнуть на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Критичность
      description: Насколько критична эта ошибка?
      options:
        - Low (косметическая проблема)
        - Medium (функциональность работает с ограничениями)
        - High (ключевая функциональность не работает)
        - Critical (приложение не работает)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Компонент
      description: В каком компоненте обнаружена ошибка?
      options:
        - Backend API
        - Frontend UI
        - Database
        - Authentication
        - File Upload
        - Notifications
        - Docker/Deployment
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Окружение
      description: Информация об окружении где воспроизводится ошибка
      placeholder: |
        - OS: [например, Windows 10, macOS 12.0, Ubuntu 20.04]
        - Browser: [например, Chrome 95, Firefox 94, Safari 15]
        - Version: [например, v1.2.3]
        - Environment: [development/staging/production]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📝 Логи/Ошибки
      description: Логи ошибок, stack traces, console output
      placeholder: Вставьте сюда релевантные логи...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Скриншоты
      description: Добавьте скриншоты если они помогут понять проблему
      placeholder: Вставьте скриншоты или drag & drop изображения сюда

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Дополнительная информация
      description: Любая дополнительная информация которая может быть полезна
      placeholder: |
        - Происходит ли ошибка только при определенных условиях?
        - Есть ли workaround?
        - Когда впервые заметили проблему?

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Убедитесь что выполнили все пункты
      options:
        - label: Я проверил что похожий issue еще не создан
          required: true
        - label: Я заполнил все обязательные поля
          required: true
        - label: Я протестировал на последней версии
          required: true
        - label: Я приложил всю необходимую информацию
          required: true
