name: ✨ Feature Request
description: Предложить новую функциональность
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение новой функциональности! Детальное описание поможет нам лучше понять ваши потребности.

  - type: textarea
    id: summary
    attributes:
      label: 📋 Краткое описание
      description: Кратко опишите предлагаемую функциональность
      placeholder: Опишите что вы хотели бы добавить...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Проблема/Потребность
      description: Какую проблему решает эта функциональность?
      placeholder: |
        Например: 
        - Сейчас сложно сделать X потому что...
        - Пользователям нужно Y для...
        - Отсутствует возможность Z что приводит к...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Предлагаемое решение
      description: Детальное описание того как должна работать функциональность
      placeholder: |
        Опишите как должна работать новая функциональность:
        - Как пользователь будет взаимодействовать с ней?
        - Какой должен быть user experience?
        - Какие должны быть результаты?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Приоритет
      description: Насколько важна эта функциональность?
      options:
        - Low (nice to have)
        - Medium (важно для user experience)
        - High (критично для бизнес-процессов)
        - Critical (блокирует ключевые сценарии)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ Компонент
      description: К какому компоненту относится функциональность?
      options:
        - Backend API
        - Frontend UI
        - Database
        - Authentication
        - File Upload
        - Notifications
        - Admin Panel
        - Mobile App
        - Integration
        - DevOps/CI-CD
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: 👤 User Stories
      description: Опишите пользовательские сценарии
      placeholder: |
        Как [роль пользователя], я хочу [действие], чтобы [результат/цель].
        
        Например:
        - Как администратор, я хочу видеть статистику использования, чтобы понимать популярность функций
        - Как пользователь, я хочу экспортировать данные в Excel, чтобы анализировать их офлайн
      render: markdown

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Wireframes
      description: Прикрепите mockups, wireframes или скриншоты для UI функций
      placeholder: Drag & drop изображения или вставьте ссылки на дизайн...

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Альтернативные решения
      description: Рассматривали ли вы другие способы решения проблемы?
      placeholder: |
        - Можно было бы сделать X, но...
        - Альтернатива Y не подходит потому что...
        - Временный workaround: ...

  - type: textarea
    id: technical_notes
    attributes:
      label: 🔧 Технические заметки
      description: Технические детали или ограничения которые стоит учесть
      placeholder: |
        - API должно поддерживать...
        - Требуется интеграция с...
        - Ограничения производительности...
        - Совместимость с...

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: ⚠️ Breaking Changes
      description: Может ли эта функциональность сломать существующий функционал?
      options:
        - label: Эта функциональность может потребовать breaking changes
        - label: Необходимо учесть обратную совместимость
        - label: Потребуются миграции данных

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ Критерии приемки
      description: Как мы поймем что функциональность готова?
      placeholder: |
        - [ ] Пользователь может...
        - [ ] Система показывает...
        - [ ] Данные сохраняются...
        - [ ] Ошибки обрабатываются...
        - [ ] Производительность не хуже...

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Дополнительная информация
      description: Ссылки, примеры из других продуктов, research
      placeholder: |
        - Похожая функциональность в [продукт]: [ссылка]
        - Исследование пользователей: [ссылка]
        - Техническая документация: [ссылка]

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Убедитесь что выполнили все пункты
      options:
        - label: Я проверил что такой feature request еще не создан
          required: true
        - label: Я подумал об альтернативных решениях
          required: true
        - label: Я описал бизнес-value этой функциональности
          required: true
        - label: Я готов участвовать в обсуждении и уточнениях
          required: true 