"""Add confidence_score to comment_keyword_matches

Revision ID: add_confidence_score
Revises:
Create Date: 2024-12-19 21:03:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_confidence_score"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment_keyword_matches",
        sa.Column("confidence_score", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comment_keyword_matches", "confidence_score")
    # ### end Alembic commands ###
