"""Make published_at nullable in vk_posts table

Revision ID: make_published_at_nullable
Revises: add_confidence_score
Create Date: 2025-01-11 18:49:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "make_published_at_nullable"
down_revision = "add_confidence_score"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_posts', 'published_at',
                    existing_type=sa.DateTime(timezone=True),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_posts', 'published_at',
                    existing_type=sa.DateTime(timezone=True),
                    nullable=False)
    # ### end Alembic commands ###
