"""add monitoring fields to vk groups

Revision ID: 20250115000000
Revises: f58c81a1f7fd
Create Date: 2025-01-15 00:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250115000000"
down_revision = "f58c81a1f7fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_groups",
        sa.Column("auto_monitoring_enabled", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("monitoring_interval_minutes", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("next_monitoring_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("monitoring_priority", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("monitoring_runs_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("last_monitoring_success", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "vk_groups",
        sa.Column("last_monitoring_error", sa.Text(), nullable=True),
    )

    # Устанавливаем значения по умолчанию
    op.execute(
        "UPDATE vk_groups SET auto_monitoring_enabled = false WHERE auto_monitoring_enabled IS NULL"
    )
    op.execute(
        "UPDATE vk_groups SET monitoring_interval_minutes = 60 WHERE monitoring_interval_minutes IS NULL"
    )
    op.execute(
        "UPDATE vk_groups SET monitoring_priority = 5 WHERE monitoring_priority IS NULL"
    )
    op.execute(
        "UPDATE vk_groups SET monitoring_runs_count = 0 WHERE monitoring_runs_count IS NULL"
    )

    # Делаем поля NOT NULL после установки значений по умолчанию
    op.alter_column(
        "vk_groups",
        "auto_monitoring_enabled",
        existing_type=sa.Boolean(),
        nullable=False,
    )
    op.alter_column(
        "vk_groups",
        "monitoring_interval_minutes",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "vk_groups",
        "monitoring_priority",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "vk_groups",
        "monitoring_runs_count",
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_groups", "last_monitoring_error")
    op.drop_column("vk_groups", "last_monitoring_success")
    op.drop_column("vk_groups", "monitoring_runs_count")
    op.drop_column("vk_groups", "monitoring_priority")
    op.drop_column("vk_groups", "next_monitoring_at")
    op.drop_column("vk_groups", "monitoring_interval_minutes")
    op.drop_column("vk_groups", "auto_monitoring_enabled")
    # ### end Alembic commands ###
