"""Add group_vk_id field to Comment model

Revision ID: 7bd888354bf6
Revises: 26eb90aa45dc
Create Date: 2025-09-08 16:29:11.342002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bd888354bf6"
down_revision: Union[str, Sequence[str], None] = "26eb90aa45dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_comments", sa.Column("group_vk_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_vk_comments_group_vk_id"),
        "vk_comments",
        ["group_vk_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vk_comments_group_vk_id"), table_name="vk_comments")
    op.drop_column("vk_comments", "group_vk_id")
    # ### end Alembic commands ###
