"""initial migration

Revision ID: 84629a3c9ad3
Revises:
Create Date: 2025-07-07 10:21:00.000000

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "84629a3c9ad3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
