"""add post_vk_id to vk_comments

Revision ID: add_post_vk_id_to_vk_comments
Revises: 999999999999
Create Date: 2025-07-21 20:31:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add_post_vk_id_to_vk_comments'
down_revision: Union[str, None] = '33ad0550f6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_comments', sa.Column('post_vk_id', sa.Integer(), nullable=True, comment='ID поста в VK (для формирования ссылок)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_comments', 'post_vk_id')
    # ### end Alembic commands ### 