"""fix: add nullable=False for created_at/updated_at in base model

Revision ID: bce7a0c9bf4a
Revises: dde5a46a2918
Create Date: 2025-07-07 10:37:13.115324

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bce7a0c9bf4a"
down_revision: Union[str, None] = "dde5a46a2918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
