"""fix: add default for created_at in vk_groups

Revision ID: dde5a46a2918
Revises: f58c81a1f7fd
Create Date: 2025-07-07 10:23:00.483136

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dde5a46a2918"
down_revision: Union[str, None] = "f58c81a1f7fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
