# Reusable Frontend Tests Workflow
# Best practices: pin actions, timeouts, minimal permissions, concurrency, matrix, cache, upload coverage, DRY, comments

on:
  workflow_call:
    inputs:
      node-versions:
        description: 'Node.js versions to test against'
        required: false
        default: '["18", "20"]'
        type: string
      upload-coverage:
        description: 'Upload coverage to Codecov and as artifact'
        required: false
        default: '"true"'
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

# concurrency:
#   group: frontend-test-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  frontend-lint:
    uses: ./.github/workflows/steps-lint.yml
    with:
      target: frontend
      node-version: '20'
    permissions:
      contents: read
    concurrency:
      group: frontend-lint-${{ github.ref }}
      cancel-in-progress: true

  frontend-test:
    needs: frontend-lint
    uses: ./.github/workflows/steps-test.yml
    with:
      target: frontend
      node-version: '20'
      upload-coverage: 'true'
    permissions:
      contents: read
    concurrency:
      group: frontend-test-${{ github.ref }}
      cancel-in-progress: true
