name: Reusable Frontend Tests

on:
  workflow_call:

env:
  NODE_VERSION_DEFAULT: '20'

jobs:
  frontend-lint:
    name: ⚛️ Frontend Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Setup Node.js ${{ env.NODE_VERSION_DEFAULT }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION_DEFAULT }}
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: |
          pnpm run lint
          pnpm run type-check
          pnpm run format:check

  frontend-test:
    name: ⚛️ Frontend Tests (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    needs: frontend-lint
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20']
    defaults:
      run:
        working-directory: ./frontend
    env:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Run tests
        run: pnpm test -- --coverage --watchAll=false

      - name: Upload coverage to Codecov
        if: matrix.node-version == env.NODE_VERSION_DEFAULT
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./frontend/coverage/lcov.info
          flags: frontend
          fail_ci_if_error: false 