name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: ["1.2.19"]
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun ${{matrix.bun-version}}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{matrix.bun-version}}
      
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test