name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-vesion: [22.x]
    
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-vesion}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-vesion}}
          cache: 'bun'
      
      - name: Install dependencies
        run: bun ci

      - name: Run tests
        run: bun test