name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: ["1.2.19"]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun ${{matrix.bun-version}}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{matrix.bun-version}}

      - name: Install backend dependencies
        working-directory: backend
        run: bun install

      - name: Run backend tests
        working-directory: backend
        env:
          DATABASE_URL: postgres://postgres:testpass@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
        run: bun test

      - name: Install frontend dependencies
        working-directory: frontend
        run: bun install

      - name: Run frontend tests
        working-directory: frontend
        run: bun test || echo "No frontend tests configured"